export const FETCH_PROFILE_REQUEST = 'FETCH_PROFILE_REQUEST'
export const FETCH_PROFILE_SUCCESS = 'FETCH_PROFILE_SUCCESS'
export const FETCH_PROFILE_FAILURE = 'FETCH_PROFILE_FAILURE'

export const FETCH_LOGIN_REQUEST = "FETCH_LOGIN_REQUEST";
export const FETCH_LOGIN_SUCCESS = "FETCH_LOGIN_SUCCESS";
export const FETCH_LOGIN_FAILURE = "FETCH_LOGIN_FAILURE";

export const FETCH_LOGOUT_REQUEST = "FETCH_LOGOUT_REQUEST";
export const FETCH_LOGOUT_SUCCESS = "FETCH_LOGOUT_SUCCESS";
export const FETCH_LOGOUT_FAILURE = "FETCH_LOGOUT_FAILURE";

export const FETCH_REGISTRATION_REQUEST = "FETCH_REGISTRATION_REQUEST";
export const FETCH_REGISTRATION_SUCCESS = "FETCH_REGISTRATION_SUCCESS";
export const FETCH_REGISTRATION_FAILURE = "FETCH_REGISTRATION_FAILURE";

export const FETCH_VERIFY_REQUEST = "FETCH_VERIFY_REQUEST";
export const FETCH_VERIFY_SUCCESS = "FETCH_VERIFY_SUCCESS";

export const FETCH_RESETPASSWORD_REQUEST = "FETCH_RESETPASSWORD_REQUEST";
export const FETCH_RESETPASSWORD_SUCCESS = "FETCH_RESETPASSWORD_SUCCESS";
export const FETCH_RESETPASSWORD_FAILURE = "FETCH_RESETPASSWORD_SUCCESS";

export const FETCH_EMAILCHANGE_REQUEST = "FETCH_EMAILCHANGE_REQUEST";
export const FETCH_EMAILCHANGE_SUCCESS = "FETCH_EMAILCHANGE_SUCCESS";
export const FETCH_EMAILCHANGE_FAILURE = "FETCH_EMAILCHANGE_FAILURE";

export const FETCH_USERINFOCHANGE_REQUEST = "FETCH_USERINFOCHANGE_REQUEST";
export const FETCH_USERINFOCHANGE_SUCCESS = "FETCH_USERINFOCHANGE_SUCCESS";
export const FETCH_USERINFOCHANGE_FAILURE = "FETCH_USERINFOCHANGE_FAILURE";

export const FETCH_USERNAMECHANGE_REQUEST = "FETCH_USERNAMECHANGE_REQUEST";
export const FETCH_USERNAMECHANGE_SUCCESS = "FETCH_USERNAMECHANGE_SUCCESS";
export const FETCH_USERNAMECHANGE_FAILURE = "FETCH_USERNAMECHANGE_FAILURE";

export const FETCH_PASSWORDCHANGE_REQUEST = "FETCH_PASSWORDCHANGE_REQUEST";
export const FETCH_PASSWORDCHANGE_SUCCESS = "FETCH_PASSWORDCHANGE_SUCCESS";
export const FETCH_PASSWORDCHANGE_FAILURE = "FETCH_PASSWORDCHANGE_FAILURE";